// src/components/characters/mockCharacters.js
const mockCharacters = [
  {
    _id: '1',
    knownAs: 'Superman',
    OriginalName: 'Clark Kent',
    BirthDate: '1986-06-18',
    character: ['Brave', 'Honest', 'Selfless'],
    interest: ['Journalism', 'Justice'],
    weapon: ['Fists', 'Heat Vision'],
    capability: ['Flight', 'Super Strength', 'X-Ray Vision'],
    powers: ['Invulnerability', 'Super Speed'],
    height: '6\'3"',
    weight: '235 lbs',
    age: '35',
    species: 'Kryptonian',
    eyes: 'Blue',
    hair: 'Black',
    limitation: ['Kryptonite', 'Magic'],
    description: 'Last son of Krypton and Earth\'s greatest hero.',
    storylineText: 'Sent to Earth as a baby before his home planet Krypton exploded, Clark Kent was raised by farmers and discovered his powers as he grew up.',
    storylineImage: 'https://via.placeholder.com/400x300?text=Superman+Story',
    originText: 'Born on Krypton to Jor-El and Lara, Kal-El was sent to Earth moments before Krypton\'s destruction.',
    originImage: 'https://via.placeholder.com/400x300?text=Superman+Origin',
    about: 'Superman stands for truth, justice, and a better tomorrow. He uses his incredible powers to protect Earth from threats both domestic and cosmic.',
    gender: 'male',
    mainImage: 'https://via.placeholder.com/200x200?text=Superman',
  },
  {
    _id: '2',
    knownAs: 'Batman',
    OriginalName: 'Bruce Wayne',
    BirthDate: '1985-02-19',
    character: ['Intelligent', 'Determined', 'Strategic'],
    interest: ['Criminology', 'Martial Arts', 'Technology'],
    weapon: ['Batarangs', 'Grappling Hook', 'Utility Belt'],
    capability: ['Detective Skills', 'Martial Arts Mastery', 'Tactical Genius'],
    powers: [],
    height: '6\'2"',
    weight: '210 lbs',
    age: '38',
    species: 'Human',
    eyes: 'Blue',
    hair: 'Black',
    limitation: ['Human Physiology', 'No Superpowers'],
    description: 'The Dark Knight of Gotham City who strikes fear into criminals.',
    storylineText: 'After witnessing his parents\' murder as a child, Bruce Wayne trained his mind and body to become Batman, Gotham\'s vigilante protector.',
    storylineImage: 'https://via.placeholder.com/400x300?text=Batman+Story',
    originText: 'Born to wealthy parents Thomas and Martha Wayne, Bruce\'s life changed when they were murdered in front of him in Crime Alley.',
    originImage: 'https://via.placeholder.com/400x300?text=Batman+Origin',
    about: 'Batman is the superhero protector of Gotham City, a man dressed like a bat who fights against evil and strikes terror into the hearts of criminals everywhere.',
    gender: 'male',
    mainImage: 'https://via.placeholder.com/200x200?text=Batman',
  },
  {
    _id: '3',
    knownAs: 'Wonder Woman',
    OriginalName: 'Diana Prince',
    BirthDate: '1987-03-22',
    character: ['Compassionate', 'Warrior', 'Diplomatic'],
    interest: ['Peace', 'Truth', 'Ancient History'],
    weapon: ['Lasso of Truth', 'Bracelets of Submission', 'Sword'],
    capability: ['Superhuman Strength', 'Combat Training', 'Tactical Leadership'],
    powers: ['Immortality', 'Flight', 'Superhuman Reflexes'],
    height: '6\'0"',
    weight: '165 lbs',
    age: '5000+',
    species: 'Amazon',
    eyes: 'Blue',
    hair: 'Black',
    limitation: ['Can be injured by weapons of the gods', 'Vulnerable to piercing weapons'],
    description: 'Amazonian princess and ambassador of peace.',
    storylineText: 'Diana left her home of Themyscira to help stop World War I and discovered her calling as a protector of both innocents and truth in the world of men.',
    storylineImage: 'https://via.placeholder.com/400x300?text=Wonder+Woman+Story',
    originText: 'Sculpted from clay by her mother Queen Hippolyta and given life by the Greek gods, Diana was raised on the hidden island of Themyscira.',
    originImage: 'https://via.placeholder.com/400x300?text=Wonder+Woman+Origin',
    about: 'Wonder Woman serves as an ambassador of the Amazon people and a symbol of truth, justice, and equality in a world dominated by men.',
    gender: 'female',
    mainImage: 'https://via.placeholder.com/200x200?text=Wonder+Woman',
  }
];

export default mockCharacters;